pipeline:
  class: a2e.pipeline.Pipeline
  config:
    mode: offline
    keras_backend: plaidml.keras.backend
    input:
      class: a2e.input.TestDataInput
      config:
        data_config_path: ../a2e_data/data/400rpm.yaml
        index_column: timestamp

    preprocessing:
      - class: a2e.processing.WindowingTransformStep
        config:
          window_size: 64

    algorithm:
      class: a2e.algorithm.KerasFitAlgorithm
      config:
        create_model_function: a2e.model.create_cnn_autoencoder
        create_model_function_parameters:
          input_dimension: 64
        epochs: 500
        batch_size: 40


    #postprocessing:

    #output:
